### ISSUE TITLE
GCC 6 FTBFS: enumerator value [...] is not an integer constant expression

### ISSUE THREAD

**Issue by alvarezp** [alvarezp/superkb#7]
Superkb doesn't compile under GCC 6. See [Debian bug #811685](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811685) [1]:

> This package fails to build with GCC 6.  GCC 6 has not been released
> yet, but it's expected that GCC 6 will become the default compiler for
> stretch.
> 
> Note that only the first error is reported; there might be more.  You
> can find a snapshot of GCC 6 in experimental.  To build with GCC 6,
> you can set CC=gcc-6 CXX=g++-6 explicitly.

The reported build log is:
```
sbuild (Debian sbuild) 0.67.0 (26 Dec 2015) on dl580gen9-02.hlinux
...
I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -DPANGO_ENABLE_BACKEND -ggdb -fPIC -DVEXTRA=\"""\" -DPREFIX=/usr -DLIBDIRNAME=lib/ -Wdate-time -D_FORTIFY_SOURCE=2  -c -o puticon/puticon-gdkpixbuf.o puticon/puticon-gdkpixbuf.c
In file included from /usr/include/glib-2.0/gobject/gobject.h:26:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h:31,
                 from /usr/include/gdk-pixbuf-2.0/gdk-pixbuf-xlib/gdk-pixbuf-xlib.h:22,
                 from puticon/puticon-gdkpixbuf.c:11:
/usr/include/glib-2.0/gobject/gparam.h:166:33: error: enumerator value for 'G_PARAM_DEPRECATED' is not an integer constant expression [-Wpedantic]
   G_PARAM_DEPRECATED          = 1 << 31
                                 ^

<builtin>: recipe for target 'puticon/puticon-gdkpixbuf.o' failed
make[2]: *** [puticon/puticon-gdkpixbuf.o] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>'
Makefile:86: recipe for target 'all' failed
```

[1] Debian bug #811685: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811685

**Comment by alvarezp** [comment]
This is a bug in GObject. See [GNOME Bugzilla bug #761119](https://bugzilla.gnome.org/show_bug.cgi?id=761119) [1].

The problem lies in that `G_PARAM_DEPRECATED` is defined as `1 << 31`, which is not standard C.

[1] GNOME Bugzilla bug #761119: https://bugzilla.gnome.org/show_bug.cgi?id=761119

**Comment by alvarezp** [comment]
Apparently, we have it fixed by working around the issue.

**Comment by glinders** [comment]
Instead of  `1 << 31` you can use `((int32_t)((1UL)<<31))`

**Comment by alvarezp** [comment]
Thanks for the suggestion. Unfortunately this was not something Superkb could fix as the bug lied in GObject. Fortunately, this was finally fixed in GObject in 2016.
